"""The interface every platform store implements (SQLite today, DynamoDB next).

Behaviour every store must match (these become the shared contract tests):
- save() is idempotent: the same reading again is a duplicate, the same key with
  different values is a conflict (first value kept, the later one recorded).
- Time ranges are half-open: start <= ts < end, returned in time order.
- flags() orders by confidence (highest first), then by creation order.
- session_user() only returns a user while expires_at is strictly after now.
- The audit log is append-only and hash-chained; verify_audit_chain() returns the
  seq of the first broken entry, or None if the chain is intact.
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Iterable, Optional, Protocol, Union, runtime_checkable

from src.ingest.validate import FeederReading, MeterReading, Reading

if TYPE_CHECKING:
    from src.store import IngestResult

# SQLite uses integer flag ids; DynamoDB will use string ids derived from the flag key.
FlagId = Union[int, str]


@runtime_checkable
class Store(Protocol):
    # Lifecycle
    def close(self) -> None: ...
    def reset(self) -> None: ...

    # Registry
    def upsert_feeder(
        self,
        feeder_id: str,
        band: str,
        metadata: Optional[dict] = None,
    ) -> None: ...

    def feeder_details(self, feeder_id: str) -> Optional[dict]: ...
    def set_telemetry_sources(self, feeder_id: str, feeder_source: Optional[str] = None, meter_source: Optional[str] = None) -> None: ...
    def upsert_meter(self, meter_id: str, feeder_id: str) -> None: ...
    def feeders(self) -> list[dict]: ...
    def feeder_band(self, feeder_id: str) -> Optional[str]: ...
    def meter_feeder(self, meter_id: str) -> Optional[str]: ...
    def meter_ids(self, feeder_id: Optional[str] = None) -> list[str]: ...
    def reading_range(self) -> Optional[tuple[datetime, datetime]]: ...

    # Readings
    def save(self, readings: Iterable[Reading], result: Optional["IngestResult"] = None) -> "IngestResult": ...
    def feeder_samples(self, feeder_id: str, start: datetime, end: datetime) -> list[tuple[datetime, float]]: ...
    def feeder_readings(self, feeder_id: str, start: datetime, end: datetime) -> list[FeederReading]: ...
    def meter_readings(self, meter_id: str, start: datetime, end: datetime) -> list[MeterReading]: ...
    def conflict_count(self) -> int: ...

    # Flags
    def save_flags(self, flags: Iterable[dict]) -> int: ...
    def flags(self, status: Optional[str] = None, feeder_id: Optional[str] = None) -> list[dict]: ...
    def flag(self, flag_id: FlagId) -> Optional[dict]: ...
    def decide_flags(self, flag_ids: list[FlagId], status: str, actor: str, note: str) -> None: ...

    # Users and sessions
    def add_user(self, username: str, password_hash: str, role: str, display_name: str, meter_id: Optional[str] = None) -> None: ...
    def user(self, username: str) -> Optional[dict]: ...
    def add_session(self, token_hash: str, username: str, expires_at: datetime) -> None: ...
    def session_user(self, token_hash: str, now: datetime) -> Optional[dict]: ...
    def delete_session(self, token_hash: str) -> None: ...

    # Audit log
    def audit(self, actor: str, action: str, target: str, details: Optional[dict] = None) -> None: ...
    def audit_entries(self, limit: int = 200) -> list[dict]: ...
    def verify_audit_chain(self) -> Optional[int]: ...
